import {
  mysqlTable,
  mysqlEnum,
  serial,
  varchar,
  text,
  timestamp,
  bigint,
  int,
  boolean,
  index,
} from "drizzle-orm/mysql-core";

// ---- Agents: endpoint yang hantar log ke GelombangMaya ----
export const agents = mysqlTable("agents", {
  id: serial("id").primaryKey(),
  name: varchar("name", { length: 128 }).notNull().unique(),
  hostname: varchar("hostname", { length: 255 }),
  ip: varchar("ip", { length: 64 }),
  os: varchar("os", { length: 128 }),
  version: varchar("version", { length: 64 }),
  status: mysqlEnum("status", ["online", "offline", "degraded"]).notNull().default("offline"),
  lastSeenAt: timestamp("last_seen_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ---- Events: raw security telemetry (log lines) ----
export const events = mysqlTable(
  "events",
  {
    id: serial("id").primaryKey(),
    agentId: bigint("agent_id", { mode: "number", unsigned: true }).references(() => agents.id),
    source: varchar("source", { length: 128 }).notNull(), // sshd, nginx, firewall, app, ...
    level: mysqlEnum("level", ["debug", "info", "notice", "warning", "error", "critical"]).notNull().default("info"),
    message: text("message").notNull(),
    srcIp: varchar("src_ip", { length: 64 }),
    dstIp: varchar("dst_ip", { length: 64 }),
    user: varchar("user", { length: 128 }),
    action: varchar("action", { length: 128 }), // auth_failure, auth_success, file_change, ...
    metadata: text("metadata"), // JSON string
    eventAt: timestamp("event_at").notNull().defaultNow(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [
    index("idx_events_event_at").on(t.eventAt),
    index("idx_events_src_ip").on(t.srcIp),
    index("idx_events_action").on(t.action),
    index("idx_events_source").on(t.source),
  ],
);

// ---- Detection rules ----
export const rules = mysqlTable("rules", {
  id: serial("id").primaryKey(),
  code: varchar("code", { length: 32 }).notNull().unique(), // GM-0001
  name: varchar("name", { length: 255 }).notNull(),
  description: text("description"),
  severity: mysqlEnum("severity", ["low", "medium", "high", "critical"]).notNull().default("medium"),
  kind: mysqlEnum("kind", ["match", "threshold", "ioc"]).notNull(),
  // match: { field, pattern(regex) } | threshold: { action, count, windowSec, groupBy } | ioc: { types[] }
  config: text("config").notNull(),
  enabled: boolean("enabled").notNull().default(true),
  hits: int("hits").notNull().default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ---- Alerts generated by the detection engine ----
export const alerts = mysqlTable(
  "alerts",
  {
    id: serial("id").primaryKey(),
    ruleId: bigint("rule_id", { mode: "number", unsigned: true }).references(() => rules.id),
    agentId: bigint("agent_id", { mode: "number", unsigned: true }).references(() => agents.id),
    title: varchar("title", { length: 255 }).notNull(),
    severity: mysqlEnum("severity", ["low", "medium", "high", "critical"]).notNull(),
    status: mysqlEnum("status", ["open", "acknowledged", "resolved", "false_positive"]).notNull().default("open"),
    detail: text("detail"),
    srcIp: varchar("src_ip", { length: 64 }),
    eventCount: int("event_count").notNull().default(1),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow().onUpdateNow(),
  },
  (t) => [index("idx_alerts_status").on(t.status), index("idx_alerts_created").on(t.createdAt)],
);

// ---- Threat intel IOCs ----
export const iocs = mysqlTable("iocs", {
  id: serial("id").primaryKey(),
  type: mysqlEnum("type", ["ip", "domain", "hash", "url"]).notNull(),
  value: varchar("value", { length: 512 }).notNull().unique(),
  description: varchar("description", { length: 512 }),
  severity: mysqlEnum("severity", ["low", "medium", "high", "critical"]).notNull().default("high"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export type Agent = typeof agents.$inferSelect;
export type Event = typeof events.$inferSelect;
export type Rule = typeof rules.$inferSelect;
export type Alert = typeof alerts.$inferSelect;
export type Ioc = typeof iocs.$inferSelect;
